> start [ALPHA][NUM]!& ID
> start ' quote
> start # comment
> start [SPACE] start
> ID [ALPHA][NUM]()[]{}_,:;& ID
> quote [ANY] quote
> quote \ escape
> quote ' QUOTE
> escape [ANY] quote
> comment [ANY] comment
> comment [LF] start
